/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as MethodologyRouteImport } from './routes/methodology'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ResourcesIndexRouteImport } from './routes/resources/index'
import { Route as ResourcesSlugRouteImport } from './routes/resources/$slug'
import { Route as ServicesIndexRouteImport } from './routes/services/index'
import { Route as ServicesAiSearchRouteImport } from './routes/services/ai-search'
import { Route as ServicesContentArchitectureRouteImport } from './routes/services/content-architecture'
import { Route as ServicesTechnicalSeoRouteImport } from './routes/services/technical-seo'
import { Route as WorkIndexRouteImport } from './routes/work/index'
import { Route as WorkSlugRouteImport } from './routes/work/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodologyRoute = MethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesIndexRoute = ResourcesIndexRouteImport.update({
  id: '/resources/',
  path: '/resources/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesSlugRoute = ResourcesSlugRouteImport.update({
  id: '/resources/$slug',
  path: '/resources/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesAiSearchRoute = ServicesAiSearchRouteImport.update({
  id: '/services/ai-search',
  path: '/services/ai-search',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesContentArchitectureRoute =
  ServicesContentArchitectureRouteImport.update({
    id: '/services/content-architecture',
    path: '/services/content-architecture',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesTechnicalSeoRoute = ServicesTechnicalSeoRouteImport.update({
  id: '/services/technical-seo',
  path: '/services/technical-seo',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkIndexRoute = WorkIndexRouteImport.update({
  id: '/work/',
  path: '/work/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkSlugRoute = WorkSlugRouteImport.update({
  id: '/work/$slug',
  path: '/work/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/contact': typeof ContactRoute
  '/methodology': typeof MethodologyRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/services/ai-search': typeof ServicesAiSearchRoute
  '/services/content-architecture': typeof ServicesContentArchitectureRoute
  '/services/technical-seo': typeof ServicesTechnicalSeoRoute
  '/work/$slug': typeof WorkSlugRoute
  '/resources/': typeof ResourcesIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/work/': typeof WorkIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/contact': typeof ContactRoute
  '/methodology': typeof MethodologyRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/services/ai-search': typeof ServicesAiSearchRoute
  '/services/content-architecture': typeof ServicesContentArchitectureRoute
  '/services/technical-seo': typeof ServicesTechnicalSeoRoute
  '/work/$slug': typeof WorkSlugRoute
  '/resources': typeof ResourcesIndexRoute
  '/services': typeof ServicesIndexRoute
  '/work': typeof WorkIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/contact': typeof ContactRoute
  '/methodology': typeof MethodologyRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/services/ai-search': typeof ServicesAiSearchRoute
  '/services/content-architecture': typeof ServicesContentArchitectureRoute
  '/services/technical-seo': typeof ServicesTechnicalSeoRoute
  '/work/$slug': typeof WorkSlugRoute
  '/resources/': typeof ResourcesIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/work/': typeof WorkIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit'
    | '/contact'
    | '/methodology'
    | '/pricing'
    | '/privacy'
    | '/terms'
    | '/resources/$slug'
    | '/services/ai-search'
    | '/services/content-architecture'
    | '/services/technical-seo'
    | '/work/$slug'
    | '/resources/'
    | '/services/'
    | '/work/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit'
    | '/contact'
    | '/methodology'
    | '/pricing'
    | '/privacy'
    | '/terms'
    | '/resources/$slug'
    | '/services/ai-search'
    | '/services/content-architecture'
    | '/services/technical-seo'
    | '/work/$slug'
    | '/resources'
    | '/services'
    | '/work'
  id:
    | '__root__'
    | '/'
    | '/audit'
    | '/contact'
    | '/methodology'
    | '/pricing'
    | '/privacy'
    | '/terms'
    | '/resources/$slug'
    | '/services/ai-search'
    | '/services/content-architecture'
    | '/services/technical-seo'
    | '/work/$slug'
    | '/resources/'
    | '/services/'
    | '/work/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditRoute: typeof AuditRoute
  ContactRoute: typeof ContactRoute
  MethodologyRoute: typeof MethodologyRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  ResourcesSlugRoute: typeof ResourcesSlugRoute
  ServicesAiSearchRoute: typeof ServicesAiSearchRoute
  ServicesContentArchitectureRoute: typeof ServicesContentArchitectureRoute
  ServicesTechnicalSeoRoute: typeof ServicesTechnicalSeoRoute
  WorkSlugRoute: typeof WorkSlugRoute
  ResourcesIndexRoute: typeof ResourcesIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
  WorkIndexRoute: typeof WorkIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methodology': {
      id: '/methodology'
      path: '/methodology'
      fullPath: '/methodology'
      preLoaderRoute: typeof MethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/': {
      id: '/resources/'
      path: '/resources'
      fullPath: '/resources/'
      preLoaderRoute: typeof ResourcesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/$slug': {
      id: '/resources/$slug'
      path: '/resources/$slug'
      fullPath: '/resources/$slug'
      preLoaderRoute: typeof ResourcesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/ai-search': {
      id: '/services/ai-search'
      path: '/services/ai-search'
      fullPath: '/services/ai-search'
      preLoaderRoute: typeof ServicesAiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/content-architecture': {
      id: '/services/content-architecture'
      path: '/services/content-architecture'
      fullPath: '/services/content-architecture'
      preLoaderRoute: typeof ServicesContentArchitectureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/technical-seo': {
      id: '/services/technical-seo'
      path: '/services/technical-seo'
      fullPath: '/services/technical-seo'
      preLoaderRoute: typeof ServicesTechnicalSeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/': {
      id: '/work/'
      path: '/work'
      fullPath: '/work/'
      preLoaderRoute: typeof WorkIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/$slug': {
      id: '/work/$slug'
      path: '/work/$slug'
      fullPath: '/work/$slug'
      preLoaderRoute: typeof WorkSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditRoute: AuditRoute,
  ContactRoute: ContactRoute,
  MethodologyRoute: MethodologyRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  ResourcesSlugRoute: ResourcesSlugRoute,
  ServicesAiSearchRoute: ServicesAiSearchRoute,
  ServicesContentArchitectureRoute: ServicesContentArchitectureRoute,
  ServicesTechnicalSeoRoute: ServicesTechnicalSeoRoute,
  WorkSlugRoute: WorkSlugRoute,
  ResourcesIndexRoute: ResourcesIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
  WorkIndexRoute: WorkIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
